[window]
dynamic_padding = true
padding = { x = 14, y = 14 }
decorations = "transparent"
opacity = 0.9
blur = true
option_as_alt = "OnlyRight"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 13
# offset = { y = 7 }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282a36"
foreground = "#eff0eb"

[colors.cursor]
cursor = "#97979b"

[colors.selection]
text = "#282a36"
background = "#feffff"

[colors.normal]
black = "#282a36"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#f1f1f0"

[colors.bright]
black = "#686868"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#eff0eb"
