#!/bin/bash

run_additional() {
cat <<EOT

Additional software to install from AppStore

  Divvy
  Pixelmator
  Timing
  Unarchiver

Addition non-AppStore software (run "dotfiles -o" to open in browser)

  1Password - https://agilebits.com/downloads
  Adobe Source Code Pro - https://github.com/adobe-fonts/source-code-pro/releases
  BitTorrent Sync - https://www.resilio.com/individuals/
  Dropbox - https://www.dropbox.com/install
  ImageOptim - https://imageoptim.com
  Slack - https://slack.com/downloads
  VSCode - https://code.visualstudio.com
  XCA - http://sourceforge.net/projects/xca/

EOT

}
