#!/bin/bash

run_download() {
e_header "Opening pages of third-party applications..."

open https://github.com/adobe-fonts/source-code-pro/releases
open https://www.getsync.com/intl/de/
open https://www.docker.com/docker-toolbox
open https://www.dropbox.com/install
open https://imageoptim.com
open http://www.sublimetext.com/3
open http://sourceforge.net/projects/xca/
}
