#!/bin/bash

run_node() {
	# https://docs.npmjs.com/getting-started/fixing-npm-permissions
	seek_confirmation "Change the owner of npm's directory's to the current user?"
	if is_confirmed; then
		sudo chown -R `whoami` `npm config get prefix`
	fi

	# update npm
	npm install -g npm

	# nave
	npm i -g nave

	# install iojs
	nave install latest

	# install node
	nave install stable

	# use iojs
	nave usemain latest

	npm i -g jshint jscs couchsurfer create-module http-server json
}
