#!/bin/bash

run_node() {
	# https://docs.npmjs.com/getting-started/fixing-npm-permissions
	seek_confirmation "Change the owner of npm's directory's to the current user?"
	if is_confirmed; then
		sudo chown -R `whoami` `npm config get prefix`
	fi

	# update npm
	npm install -g npm

	# nave
	npm i -g nave

	# install node
	nave install stable
	nave usemain stable

	npm i -g standard couchsurfer create-module http-server json

	# install npm tab completion
	npm completion > /usr/local/etc/bash_completion.d/npm
}
